# Generated by Django 3.1.1 on 2020-09-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_user1',
            new_name='user_type1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_user2',
            new_name='user_type2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_user3',
            new_name='user_type3',
        ),
    ]
